baseURL = 'http://sarahjalexander.com/'
languageCode = 'en-us'
title = 'Learning to code'
theme = 'anatole'

[params]
title = "Sarah Alexander"
author = "Sarah Alexander"
description = "LIFELONG LEARNER"
profilePicture = "images/sarah-profile.jpg"

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"