baseURL = 'http://sarahjalexander.com/'
languageCode = 'en-us'
title = 'Learning to code'
theme = 'anatole'

# allow script tags in my content
# as per https://discourse.gohugo.io/t/javascript-on-page/4166/8
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
title = "Sarah Alexander"
author = "Sarah Alexander"
description = "LIFELONG LEARNER"
profilePicture = "images/sarah-profile.jpg"
contentratio = 0.7

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/sarahjalexander/"
[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:sjalex78@gmail.com"

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"