baseURL = 'http://sarahjalexander.com/'
languageCode = 'en-us'
title = 'Learning to code'
theme = 'anatole'

[params]
title = "I'm Sarah Alexander"
author = "Sarah Alexander"
description = "Call me Sarah"
profilePicture = "images/sarah-profile.jpg"