baseURL = 'http://sarahjalexander.com/'
languageCode = 'en-us'
title = 'Learning to code'
theme = 'anatole'

# allow script tags in my content
# as per https://discourse.gohugo.io/t/javascript-on-page/4166/8
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
title = "Sarah Alexander"
author = "Sarah Alexander"
description = "LIFELONG LEARNER"
profilePicture = "images/sarah-profile.jpg"
contentratio = 0.8
##mainSections = []
displayMode = "dark"
readMore = true

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/sarahjalexander/"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:sjalex78@gmail.com"

[[params.socialIcons]]
icon = "fab fa-fw fa-github"
title = "github"
url = "https://github.com/sjalex78"

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"


  [[menu.main]]
  name = "Reflect"
  weight = 300
  identifier = "blog"
  url = "/posts/"


  [[menu.main]]
  name = "Resume"
  weight = 300
  identifier = "resume"
  url = "/resume/"

  [[menu.main]]
  name = "Portfolio"
  weight = 300
  identifier = "portfolio"
  url = "/portfolio/"

  [[menu.main]]
  name = "Teaching"
  weight = 300
  identifier = "teaching"
  url = "/teaching/"

  [[menu.main]]
  name = "Science"
  weight = 300
  identifier = "science"
  url = "/science/"


  [[menu.main]]
  name = "L&L"
  weight = 300
  identifier = "loaf&lily"
  url = "/loaflily/"
